name: Continuous deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: '18.14.0'
      
    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: milanbrock/swaptemreact:latestversion

    - name: Log out from Dockerhub
      run: docker logout https://hub.docker.com/
