name: React CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env: 
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Install testing library
        run: npm install --save-dev @testing-library/dom
      - name: Run build 
        run: npm run build --if-present
